### ISSUE TITLE
如何查看是否運作

### ISSUE THREAD

**Issue by mk2leo** [spiritLHLS/proxyrack-one-click-command-installation#1]
一鍵腳本運行了..但如何查看運作.proxyrack的DEVICES中也沒看見設備.

**Comment by spiritLHLS** [comment]
执行docker ps -a 可以看到正在运行的容器，注意目前官方只支持AMD架构，不支持arm架构，部署完毕后大概几分钟后会在后台显示，非实时

**Comment by mk2leo** [comment]
> 等了半個小時也不見後台自動掛上..手動提取了ID.在後台手動填上了..

**Comment by spiritLHLS** [comment]
这就奇怪了，不可能不显示的阿
执行
```
docker logs proxyrack
```
看看日志吧，没日志我也搞不懂有什么问题，我自己的运行是没有问题的

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/proxyrack-one-click-command-installation/commit/6b49f0929c0d3584cfdd9f002ce0995dd2bcd9a3

更新打印输出对应的信息，如果长时间未见其在后台显示，可手动录入（目前我正在测试是否真自动录不进去，自动录不进去就是官方的BUG了）

**Comment by spiritLHLS** [comment]
> > 等了半個小時也不見後台自動掛上..手動提取了ID.在後台手動填上了..

感觉是官方BUG，找客服反馈了，也做了补救措施安装完毕打印信息，有新信息会及时更新
